// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
//
// Hand-edited: the client is imported inside the handler, not at the top of this
// file, so start.ts doesn't pull supabase-js into the startup bundle. It only
// loads when a serverFn is actually called. If this file is regenerated with a
// static import again, src/test/supabase-lazy.test.ts fails.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
